version: '3.9'

services:
  django:
    container_name: django
    build: server/.
    command: python blog/manage.py runserver 0.0.0.0:8080
    volumes:
      - ./server:/app/
    ports:
      - '8080:8080'

#  frontend:
#    container_name: frontend
#    build: client/.
#    volumes:
#      - ./client:/app/
#    ports:
#      - '3000:3000'

