# Generated by Django 4.1.7 on 2023-04-03 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_comment_options'),
        ('post', '0005_alter_postcategory_name'),
    ]

    operations = [
    ]
